Fixed #11875. Enclosed configuration Frame in ScrollViewer to keep scroll position in settings pages
microsoft/terminal pull request #12296
Opened 2022-01-31 03:05 UTC by Jcabza008

## Summary of the Pull Request
This PR attempts to solve issue #11875. I was able to make the scroll position persistent by enclosing the `Frame` in a `ScrollViewer`. Currently, the existing animation allows you to see that a reload happened, but the scroll position is never changed.

## PR Checklist
* [x] Closes #11875 
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #11875.

## Validation Steps Performed
I manually tested this behavior.

2022-01-31 12:03 UTC, zadjii-msft commented
Thanks for doing this! I wanna make sure that this doesn't introduce two scrollbars, kinda like in #10664. I'll check this branch out later and double check

2022-02-01 13:14 UTC, zadjii-msft commented
Oaky so this works fine with always show scrollbars, so that's a good sign 👍 

Maybe something unexpected - Now the scroll position is always maintained across pages. So, for example, navigate to a profile's appearance page, scroll all the way down, then click on the actions page. That will now open scrolled down part of the way. 

I'm not sure there's a clever way to avoid that. Maybe we can manually reset the scroll position when we navigate to a _different_ page, but I'm not sure how we could determine that. @carlos-zamora and @PankajBhojwani to see if they have any clever ideas.

2022-02-03 18:19 UTC, carlos-zamora commented
> Maybe something unexpected - Now the scroll position is always maintained across pages. So, for example, navigate to a profile's appearance page, scroll all the way down, then click on the actions page. That will now open scrolled down part of the way.
> 
> I'm not sure there's a clever way to avoid that. Maybe we can manually reset the scroll position when we navigate to a _different_ page, but I'm not sure how we could determine that.

This code block might be of use to you:
https://github.com/microsoft/terminal/blob/e064c1567548f098233b7a2d1101cb5201dec049/src/cascadia/TerminalSettingsEditor/MainPage.cpp#L138-L169

Here, we've loaded the settings again after the "discard changes" or "save" button was clicked. This code block specifically is trying to find the page we were already on so we can navigate to it (making it look like you never left the page).

We want _the opposite_ of this, so in our `_Navigate()`s you'll probably just want to check if the page is different by comparing the tag to the currently selected one, and if it's different, reset the scroll position.

Hope this helps 🙂

2022-02-03 18:21 UTC, carlos-zamora requested changes
Blocking until the issue above gets resolved.

2022-02-18 01:01 UTC, closed without merging