Switch to VS17 and C++20
microsoft/terminal pull request #13368
Opened 2022-06-23 15:03 UTC by lhecker

C++20 goodies include:
* 3-way comparison operator `<=>` and `operator==() = default`
* designated initializers
* constraints and concepts
* abbreviated function templates (`void foo(auto bar)`)
* pack-expansions in lambda init-captures
* heterogeneous lookups in `unordered_set` / `unordered_map`
* `consteval` / `constinit`
* `starts_with` / `ends_with` for `string` / `string_view`
* `midpoint`, `lerp`
* `<bit>`
* `<ranges>`
* `<span>`
* `<barrier>`
* `<latch>`
* `<semaphore>`

2022-06-23 20:47 UTC, DHowett commented on src/cascadia/TerminalConnection/CTerminalHandoff.cpp
>          auto localPfnHandoff = _pfnHandoff;
I am not the biggest fan of mechanical changes being mixed with functional and bugfix changes. :)

2022-06-23 20:52 UTC, DHowett commented on src/cascadia/TerminalConnection/CTerminalHandoff.cpp
>          auto localPfnHandoff = _pfnHandoff;
Like, I might like to backport a small race condition fix but I am not planning on backporting a whole toolchain change (for example!)

2022-06-23 23:01 UTC, DHowett requested changes
Blocking until 1.15 forks :)

2022-06-27 03:29 UTC, skyline75489 commented on .github/actions/spelling/patterns/patterns.txt
> +https?://\S+
This is actually introduced by me, who tried to be more cautious than usual 😅

2022-07-01 01:14 UTC, DHowett commented on src/cascadia/TerminalConnection/CTerminalHandoff.cpp
>          auto localPfnHandoff = _pfnHandoff;
(Would you mind bringing this change in in a separate PR?)

2022-07-05 20:12 UTC, zadjii-msft approved these changes

2022-07-05 20:21 UTC, DHowett commented on src/cascadia/WinRTUtils/inc/Utils.h
> +    // The MSVC 14.31.31103 toolset seems to misdiagnose this line.
1: spell fix the word toolset

2: we should follow the STL team's convention and use "BODGY" to indicate compiler workarounds maybe?

2022-07-05 20:21 UTC, DHowett approved these changes

2022-07-05 20:30 UTC, DHowett approved these changes

2022-07-05 21:06 UTC, merged