Upgrade to Windows SDK 22621
microsoft/terminal pull request #14135
Opened 2022-10-05 12:31 UTC by lhecker

The diff between the 22000 and 22621 SDKs is fairly small, but it does include
a number of C++ correctness fixes, updates to libraries like DirectXMath and
the latest updates to DirectWrite and DXGI which I make heavy use off.

## Validation Steps Performed
* TBD

2022-10-05 18:02 UTC, DHowett commented on src/cascadia/WindowsTerminal/WindowsTerminal.manifest
> +        <maxversiontested Id="10.0.22621.0"/>
You must _add_ another `maxversiontested`, not replace the existing one :smile: (see comment above)

2022-10-05 18:03 UTC, DHowett requested changes
-

2022-10-06 19:14 UTC, lhecker commented
@DHowett The issue should be addressed now.

2022-10-06 23:56 UTC, carlos-zamora approved these changes

2022-10-07 00:09 UTC, DHowett approved these changes
I'm cool with this, but usually we wait at least six months before adopting a new SDK. However, this might fix some of our downlevel linking issues since they fixed a couple apiset bugs. I dunno. Let's try it and see how bad it is? Our contributors may not be ready for the switch.

2022-10-07 00:09 UTC, merged