Add walkthroughs to CONTRIBUTING.md
microsoft/terminal pull request #15799
Opened 2023-08-07 11:17 UTC by zadjii-msft

Change the "good first issues" text to talk about walkthroughs instead.

2023-08-07 13:57 UTC, zadjii-msft commented
Both, both is good

2023-08-07 16:19 UTC, tusharsnx commented
Off-topic, did you just read my comment on the latest terminal showcase on yt 😅  ?

![image](https://github.com/microsoft/terminal/assets/55626797/95378486-7c5c-4ab6-9adc-d8b471892399)

2023-08-07 16:21 UTC, DHowett requested changes

2023-08-07 16:21 UTC, DHowett commented on CONTRIBUTING.md
> +The best place to start is the list of ["walkthroughs"](https://aka.ms/terminal-walkthroughs)s. This is a collection of issues where we've written a "walkthrough", a little guides to help get started
This says `"walkthroughs"s`, FWIW

2023-08-07 16:21 UTC, DHowett commented on CONTRIBUTING.md
> +The best place to start is the list of ["walkthroughs"](https://aka.ms/terminal-walkthroughs)s. This is a collection of issues where we've written a "walkthrough", a little guides to help get started
it also says "a little guide**s** to help get started"

2023-08-07 16:33 UTC, zadjii-msft commented
> Off-topic, did you just read my comment on the latest terminal showcase on yt 😅 ?

lol I didn't know that had already been posted! I thought that was supposed to be going live _this_ week 🤦 

I legit was writing a blog post to go with that video this morning and Copilot was all
![image](https://github.com/microsoft/terminal/assets/18356694/95830dc4-0afe-41bd-9c40-56d160257b9f)

to which I said "damn that's a good idea"

2023-08-10 22:09 UTC, DHowett approved these changes

2023-08-11 14:57 UTC, merged