Fixed UI capitalization and style errors.
microsoft/terminal pull request #16918
Opened 2024-03-21 21:17 UTC by Ismith507

## Summary of the Pull Request
This pull request addresses the issue opened by @PhMajerus concerning the UI and style errors in Windows Terminal

## Detailed Description of the Pull Request / Additional comments
PR is pretty straightforward. Just edited src/cascadia/TerminalApp/Resources/en-US/Resources.resw to reflect the changes desired in the issue.

This is my first contribute to a repository that is not my own. So, if I am missing any requirements in my PR or if anything needs to be changed, please let me know!

Closes #16846

2024-03-21 21:19 UTC, Ismith507 commented
@microsoft-github-policy-service agree

2024-04-09 23:56 UTC, carlos-zamora requested changes
Thanks for contributing! Sorry it's taken a while for us to review this. 

You're talking about #16846, right? I went ahead and edited your PR description, but normally, update the "Closes #xxx" text in the template to be "Closes #16846". If you want to be extra nice, remove all the extra stuff in the PR description too, but not strictly necessary. We just like linking up the relevant issues so we know what the PR is trying to address 😊.

Looking through this PR, I think updating the project files is out of scope for what you're trying to do. Please undo changes to the following files (all of them except the resw file):
- OpenConsole.sln
- src/cascadia/WindowsTerminal_UIATests/WindowsTerminal.UIA.Tests.csproj
- src/cascadia/WindowsTerminal_UIATests/app.config
- src/cascadia/WpfTerminalControl/WpfTerminalControl.csproj
- src/cascadia/WpfTerminalTestNetCore/WpfTerminalTestNetCore.csproj
- src/host/ft_uia/Host.Tests.UIA.csproj
- src/host/ft_uia/app.config
- src/tools/TerminalStress/TerminalStress.csproj
- src/tools/vtapp/App.config
- src/tools/vtapp/VTApp.csproj

Other than that, I think we're good! I'll go ahead and approve once the changes go in. Thanks!

2024-04-09 23:56 UTC, carlos-zamora commented on CppProperties.json
> +{
undo checking in this file, please

2024-04-09 23:56 UTC, carlos-zamora commented on src/cascadia/TerminalApp/Resources/en-US/Resources.resw
> +    <value>Close other Tabs</value>
```suggestion
    <value>Close other tabs</value>
```
Shouldn't "Tabs" be changed to "tabs" too? The open issue said that we should use "Sentence-style capitalization".

2024-04-09 23:56 UTC, carlos-zamora commented on src/cascadia/TerminalApp/Resources/en-US/Resources.resw
> +    <value>Third-Party notices</value>
```suggestion
    <value>Third-party notices</value>
```
Sentence style capitalization means the "p" should be lowercase

2024-04-09 23:56 UTC, carlos-zamora commented on src/cascadia/TerminalApp/Resources/en-US/Resources.resw
> +    <value>Lime green</value>
I think all of these should stay as-is, actually. They're proper nouns of the color, so guidelines state we should capitalize all of it.

2024-04-09 23:56 UTC, carlos-zamora commented on src/cascadia/TerminalApp/Resources/en-US/Resources.resw
> +    <value>Slate blue</value>
Same goes for these, should probably stay capitalized since they're proper nouns for colors.

2024-04-09 23:56 UTC, carlos-zamora commented on src/cascadia/TerminalApp/Resources/en-US/Resources.resw
> +    <value>Dark gray</value>
Same goes for these, should probably stay capitalized since they're proper nouns for colors.

2024-04-09 23:58 UTC, carlos-zamora commented
Oh! And normally you'd have to worry about the spell-checker. But I think that it's just flagging stuff in the project files that need to be untracked, so you shouldn't have to worry about it.

2024-04-10 18:41 UTC, closed without merging

2024-04-10 18:51 UTC, Ismith507 commented
Hello!

I created a new PR (#17037) that is ready for your review. I have corrected the mistakes in this PR and implemented some of the changes you suggested. I'm not sure how so many files got changed when I was working on my edits, it must have been when I was trying to build and run the project on my computer. Anyway, this new PR should limit its changes to the Resources.resw file. 

Thank you for your input!