Replace MarkKind::None with MarkKind::Output
microsoft/terminal pull request #18291
Opened 2024-12-06 21:45 UTC by lhecker

During the development of #18290 I noticed that we caused a regression
with the storage of marks in attributes. Since the default attribute is
None and any output sets it to, well, Output, this meant that every
row of output would at least temporarily allocate heap memory.
This caused cls on a huge history to take twice as long as before.

## Validation Steps Performed
* How do I test this? ❓

2024-12-06 21:48 UTC, lhecker commented on src/buffer/out/textBuffer.cpp
> -                lastMarkKind = markKind;
BTW the `lastMarkKind` variable is entirely unused. The condition above, `if (markKind != MarkKind::None)` also seems wrong to me. Is it supposed to test `lastMarkKind`?

2024-12-11 11:58 UTC, zadjii-msft requested changes
okay I haven't read the code yet, but I did check out the branch, and this definitely broke selecting output.

2024-12-11 12:15 UTC, zadjii-msft commented on src/buffer/out/textBuffer.cpp
> +            if (markKind != MarkKind::Output)
You know, entirely removing this conditional _seems_ to work, form 1 minute of playing with it

2024-12-11 20:26 UTC, lhecker commented
I'll just bump the attributes vector size from 1 to 3. That seems easier to me until we have differential compression of attributes. That is, instead of storing run-lengths, store changes-between-lengths. Removing the charOffset vector from ROW will be much more effective for reducing the ROW size than caring about the attribute vector IMO.

2024-12-11 20:26 UTC, closed without merging