Preview tab switching with the ATS
microsoft/terminal pull request #7796
Opened 2020-10-01 11:11 UTC by zadjii-msft

## Summary of the Pull Request

![preview-ats-000](https://user-images.githubusercontent.com/18356694/94801728-18302a00-03ac-11eb-851d-760b92ebb46f.gif)

This PR enables the ATS to display the active tab as the user navigates the tab switcher. We do this by dispatching the tab switch actions as the user navigates the menu, and manually _not_ focusing the new tab when the tab switcher is open. 

## References

* #6732 - original tab switcher PR
* #6689 - That's a more involved, generic version of this, but this PR will be enough to stop most of the complaints hopefully

## PR Checklist
* [x] Closes #7409
* [x] I work here
* [ ] Tests added/passed
* [n/a] Requires documentation to be updated

## Validation Steps Performed

Opened tabs, tabbed through the menu, verified that it did what I'd expect

2020-10-01 18:50 UTC, leonMSFT approved these changes
This is awesome, thanks for taking it up! 😄

Possibly unrelated to this PR - but I wonder if those same people complaining would also want tab preview when using `Tab Search`? 🤔 The argument about tab titles being useless still applies there, but perhaps less so.

2020-10-01 18:52 UTC, zadjii-msft commented
> I wonder if those same people complaining would also want tab preview when using `Tab Search`? 🤔 The argument about tab titles being useless still applies there, but perhaps less so.

Oh they very well might, good catch

2020-10-04 13:55 UTC, ionut-botizan commented
Congrats guys! You now have the exact same set of features as before the ATS was added, with just some minor tweaks:
1. A list of all the tabs in the order they were opened. Previously they were only listed horizontally in the titlebar; now, in addition to the titlebar, there's a new vertical list, in a popup...
2. Quick switch to the next tab in the list when the `Tab` key is released. Really, no difference here - the visible tab was already switching to the next one before the ATS was added. You could've argued that there's something new here if you could've canceled the action, reverting to the initial tab, but you can't do that, can you? Releasing the `Ctrl` key just makes the switch permanent while pressing `Esc` while still holding `Ctrl` to dismiss the tabs list would just open the Windows Start Menu... Sooo... Yeah!

My point is: **the entire ATS is useless without the MRU switching**. People that don't use/need/want MRU are disabling the ATS because they don't need it and it's just bloat for them, while those of use that use/need/want it just cringe at your lack of focus. Really, the MRU switching (which you so prominently teased in the very first paragraph of the ATS spec) was way more important than this preview thingie...
Honestly, I'm not even mad or something at this point. I'm just sad... 😔

---

Here's a little metaphor for you, to help you understand the absurdity (in our MRU loving people's minds) of tab switching in open order, without MRU...

Imagine this scene: you're at your desk. You take a sip from your mug of coffee/tea/whatever that's in front of you. You let the mug down and put your headphones on. You move your hands on the keyboard/mouse and start working on something. So, you're in this state now. One minute passes. Now, you want to take a sip from that mug, just as you did one minute ago. How do you end up in a state where your hand is on the mug? Do you:
1. Get up, go to the kitchen, take a quick look around, have a preview of the coffee machine, open the fridge and take a peek at the milk bottle/cream tube, maybe take a quick look at the sugar jar and then return to your desk and grab the mug and drink?
2. Do it all in reverse and take your headphones off first, then you drink?
3. ...or do you simply directly perform the same action you just performed a minute ago, of moving your hand and grabbing the mug and just drink?

Do you really need to re-play all those steps that got you in the current state? Why, then, would I want to go through all those tabs over and over again when the most recent non-active one is probably the most important at any given point in time?

2020-10-04 17:37 UTC, DHowett commented
Are you intentionally being incredibly condescending? It sure seems like it.

We get it. You and the fifty other people who asked for MRU without being quite as arrogant or prickish (save one; there was one other) have made your message heard.

2020-10-05 09:27 UTC, zadjii-msft commented
@ionut-botizan Seriously dude, Rome wasn't built in a day. We're working on it, one step at a time. We're tracking MRU tab switching over in #973, so please have that discussion in that thread.

2020-10-07 15:07 UTC, PankajBhojwani approved these changes

2020-10-07 17:10 UTC, DHowett commented on src/cascadia/TerminalApp/CommandPalette.cpp
> +    }
This seems circuitous. TerminalPage is already driving the selection of tabs in the tab switcher, so  should we reduce coupling by having TerminalPage do the active terminal change in addition to driving the switching UI?

Maybe having it be in MRU order changes things.

2020-10-07 17:10 UTC, DHowett commented on src/cascadia/TerminalApp/CommandPalette.cpp
> +    }
(I'm averse to taking on too many more "are we in mode A, B, C, or D" checks :/)

2020-10-07 17:11 UTC, DHowett requested changes
block for chat

2020-10-07 20:41 UTC, zadjii-msft commented
Chatted with Dustin - yes this seems like extra hoops to jump through right now, but in the future, the Tab Switcher won't just have the list of tabs in the same order as the tabs themselves. The tab switcher might have them in MRU order, or it might be displaying the panes in a tab. In those cases, the page _will_ need to route the action through the switcher, so it makes sense to leave it like this for now.

2020-10-07 20:43 UTC, DHowett approved these changes

2020-10-07 21:06 UTC, zadjii-msft commented
/azp run

2020-10-07 22:49 UTC, merged

2020-10-08 12:11 UTC, mpela81 commented
Hi - I'm getting this when building master after this merge:

```4>CommandPalette.cpp
4>C:\code\windows-terminal\terminal-original\src\cascadia\TerminalApp\CommandPalette.cpp(135,75): error C2039: 'Command': is not a member of 'winrt::TerminalApp'
4>C:\code\windows-terminal\terminal-original\src\cascadia\TerminalApp\CommandPalette.cpp(20): message : see declaration of 'winrt::TerminalApp'
```

2020-10-08 16:38 UTC, carlos-zamora commented
> Hi - I'm getting this when building master after this merge:
> 
> ```c++
> 4>C:\code\windows-terminal\terminal-original\src\cascadia\TerminalApp\CommandPalette.cpp(135,75): error C2039: 'Command': is not a member of 'winrt::TerminalApp'
> 4>C:\code\windows-terminal\terminal-original\src\cascadia\TerminalApp\CommandPalette.cpp(20): message : see declaration of 'winrt::TerminalApp'
> ```

😲 oh no. This seems to have conflicted with my TerminalSettingsModel change. I'll go ahead and fix that right now. Thanks!