Document how to add a setting to Windows Terminal
microsoft/terminal pull request #8566
Opened 2020-12-12 00:53 UTC by carlos-zamora

[Markdown Preview](https://github.com/microsoft/terminal/blob/dev/cazamor/sui/add-a-setting-doc/doc/cascadia/AddASetting.md)

This guide serves as a reference on how to add a setting to Windows Terminal. It covers...
- Terminal Settings Model changes
- Settings UI changes
- `TerminalSettings` changes
- Actions and action arguments

As a part of #6800 (Settings UI Follow Up Tasks)

2020-12-14 23:06 UTC, DHowett requested changes
Looks great! Missing one thing: adding the projected setting to the ProfileViewModel idl and .h using the `PROJECTED` or `OBSERVABLE` macros.

2020-12-15 16:56 UTC, zadjii-msft approved these changes
Assuming that this has everything for the SUI, this seems good to me

2020-12-17 20:00 UTC, carlos-zamora commented
@DHowett I emphasized the section on profile settings a bit more, but let me know if I should mention anything else on that topic.

2020-12-17 20:17 UTC, DHowett commented on doc/cascadia/AddASetting.md
> +// - if the setting cannot be altered by the user, use the following macro instead:
this is incorrect. it wouldn't need to be a setting if it weren't alterable.

this is for settings that cannot be CLEARed

2020-12-18 02:09 UTC, DHowett approved these changes

2020-12-18 02:09 UTC, merged