Polish the Background Image settings
microsoft/terminal pull request #8778
Opened 2021-01-13 18:18 UTC by zadjii-msft

## Summary of the Pull Request

Two parts:
* Hide the BG image settings when no image is specified
* Add a checkbox for "Use desktop wallpaper". When that's checked, the BG image path input is hidden. Unchecking that box restores the path to what it was before.

## PR Checklist
* [x] Closes #8763
* [x] I work here

## Validation Steps Performed
Tested manually

2021-01-13 18:46 UTC, carlos-zamora approved these changes
Mind adding some pics or a gif to see what it looks like? I think I can visualize it but it'd be nice to have in the PR body.

Love the changes to converters!
Mostly nits here.

2021-01-13 18:46 UTC, carlos-zamora commented on src/cascadia/inc/cppwinrt_utils.h
> +#define DECLARE_CONVERTER(nameSpace, className)                                                                   \
Might as well use `DECLARE_CONVERTER` on all the other converter header files. For consistency.

2021-01-13 18:46 UTC, carlos-zamora commented on src/cascadia/TerminalSettingsEditor/Profiles.cpp
> +        // box, prevent it from ever being changed again.
Good catch!

2021-01-13 18:46 UTC, carlos-zamora commented on src/cascadia/TerminalSettingsEditor/Profiles.cpp
> +        if (BackgroundImagePath() != L"desktopWallpaper")
nit: should `L"desktopWallpaper"` be a `static constexpr std::wstring_view`?

2021-01-13 18:46 UTC, carlos-zamora commented on src/cascadia/TerminalSettingsEditor/Profiles.cpp
> +        if (BackgroundImagePath() != L"desktopWallpaper")
That way you just reference it below in `UseDesktopBGImage()` too

2021-01-13 18:46 UTC, carlos-zamora commented on src/cascadia/TerminalSettingsEditor/Profiles.idl
> +        Boolean UseDesktopBGImage { get; set; };
```suggestion
        Boolean UseDesktopBGImage;
```
Absence of `{ get; set; }` assumes it's there, right?

2021-01-13 18:56 UTC, zadjii-msft commented
![sui-desktopWallpaper](https://user-images.githubusercontent.com/18356694/104496447-a4064480-559e-11eb-84fb-7cc7a9130848.gif)

2021-01-13 22:05 UTC, carlos-zamora requested changes
Realized something. Make sure to disable the "hide background image settings" behavior in the "Base Layer" page. There's a good use case for customizing those settings in "Base Layer" even though you don't have a background image set.

Shouldn't be too difficult. There's an `IsBaseLayer` bool exposed off of the `ProfileViewModel` that you can use to check this.

2021-01-14 20:04 UTC, PankajBhojwani commented
I think I would prefer if the checkbox was immediately below the textbox for the path, and that the textbox and button are _disabled_ when the checkbox is set (rather than hidden), this gets us

- consistency with #8786 
- no need to have two 'background image' headers like there currently is, we could just have one
- imo its more intuitive - currently, if the user has 'desktop wallpaper' set and wants to change it, its not immediately obvious that they need to uncheck desktop wallpaper before the textbox will show. But if the textbox is greyed out when the checkbox right underneath it is checked, it becomes more obvious

Thoughts?

2021-01-14 21:24 UTC, zadjii-msft commented
![image](https://user-images.githubusercontent.com/18356694/104650951-9921e180-567c-11eb-8aa0-31b7bae30e10.png)

2021-01-14 22:02 UTC, zadjii-msft commented
> 
> 
> Realized something. Make sure to disable the "hide background image settings" behavior in the "Base Layer" page. There's a good use case for customizing those settings in "Base Layer" even though you don't have a background image set.
> 
> Shouldn't be too difficult. There's an `IsBaseLayer` bool exposed off of the `ProfileViewModel` that you can use to check this.

![image](https://user-images.githubusercontent.com/18356694/104654398-9fff2300-5681-11eb-87e8-1008ce6f06a0.png)

2021-01-14 22:24 UTC, carlos-zamora approved these changes
Thanks!

2021-01-18 22:33 UTC, DHowett approved these changes

2021-01-18 22:34 UTC, merged