Sanitize paste content by filtering out control chars
microsoft/terminal pull request #8875
Opened 2021-01-25 05:15 UTC by skyline75489

## Summary of the Pull Request

Address the security issued mentioned in https://github.com/microsoft/terminal/issues/395#issuecomment-477206196

 
## References

Supersedes #7508

## PR Checklist
* [ ] Closes #xxx
* [ ] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments

## Validation Steps Performed

2021-01-25 16:15 UTC, zadjii-msft commented
@msftbot make sure @DHowett signs off on this

2021-01-25 16:16 UTC, zadjii-msft approved these changes
This seems reasonable to me, but I want Dustin to take a look too, since he's the expert in that particular area.

2021-01-25 21:45 UTC, DHowett commented on src/cascadia/TerminalControl/TermControl.cpp
>          // Some notes on this implementation:
i'd rather we not scan the string multiple times. can we consolidate this with the loop below?

2021-01-25 22:43 UTC, DHowett requested changes
(making my NAK an actual "request changes")

2021-01-26 02:16 UTC, skyline75489 commented
I should probably mention that thanks to #8744, the potentially malicious content from the clipboard is being displayed in a dazzling dialog. This *should* prevent users from pasting it in most conditions.

![image](https://user-images.githubusercontent.com/4710575/105790307-090a6300-5fbf-11eb-9220-47626109c57e.png)

2021-01-26 03:32 UTC, skyline75489 commented
This PR will still help prevent attacks described in https://security.stackexchange.com/q/39118, where currently the dialog isn't showing invisible control character.s

![image](https://user-images.githubusercontent.com/4710575/105796556-07926800-5fca-11eb-9d21-22987de349d8.png)

2021-01-26 05:47 UTC, skyline75489 commented on src/cascadia/TerminalControl/TermControl.cpp
> +        auto pred = [](wchar_t c) {
Inlining this in `std::remove_if` results in very weird indention using `clang-format`. Nesting this inside `sanitize` crashes `clang-format`(!). So I had to put it here.

2021-01-26 05:51 UTC, skyline75489 commented on src/cascadia/TerminalControl/TermControl.cpp
> +            // CR(0x0d) and DEL(0x7F).
Removing `CR` and `LF` seems meaningless from a practical point of view. But generally I think this function *should* remove `CR` and `LF` had it not been in this particular context.

2021-01-26 05:58 UTC, skyline75489 commented on src/cascadia/TerminalControl/TermControl.cpp
> +            // CR(0x0d) and DEL(0x7F).
(copied from #7508)

The best resource I can find is here https://security.stackexchange.com/a/52655. It suggest removing every control characters except:

* CR(0x0d) \r 
* LF(0x0a) \n 
* HT(0x09) \t, 
* DEL(0x7F)

Then there's some other opinions in https://bugzilla.gnome.org/show_bug.cgi?id=753197, regarding removing:

* 0x80-0x9F

And here https://bugzilla.gnome.org/show_bug.cgi?id=794653, regarding removing:

* BS(0x08)
* DEL(0x7F)

2021-01-26 18:49 UTC, jantari commented
I just want to say I do intentionally paste text with VT control sequences into the terminal, usually just for colors or other effects. So I'm not sure how I feel about `0x1b` aka `ESC` being stripped

2021-01-26 18:53 UTC, DHowett commented
I suspect you are in the minority here. Many other terminal applications filter out control characters during bracketed paste, and _an application shouldn't be expecting to receive raw SGRs in its input stream anyway_.

2021-01-26 20:51 UTC, jantari commented
Yea I understand that, but what about an option - either in the JSON config, or directly in the new paste dialog:

![paste-confirmation](https://user-images.githubusercontent.com/4710575/105796556-07926800-5fca-11eb-9d21-22987de349d8.png)

When it detects non-printable or control-characters in the text, it could present a third, non-focused button: "Paste with special characters"

2021-01-26 21:58 UTC, DHowett commented
It's just that... every setting we add is another combinatorial factor in our testing, right? There's already `sendInput` for sending raw controlled input. I just don't see the use case for pasting control characters today..?

2021-01-26 22:48 UTC, jantari commented
Good point, possible usecases were testing string snippets for shell prompts (bash `$PS1` or powershells' `prompt` function) or other snippets of fancy text. It's not a big issue though, by now I've more or less switched entirely to shell-sequences like `\033` in bash or the ugly `$([char]27)` in powershell to get `ESC` rather than a raw `ESC` character

Since you said `SendInput` is not affected by this behavior/change - I assume the same holds true for `WriteConsoleInput`?

2021-01-26 22:51 UTC, DHowett commented
The code change in this file, and the policy we're instating here, implicates **only** paste.

We're not breaking Win32 APIs willy-nilly. :smile:

Also: PowerShell Core supports "`e" for escaping escape.

2021-01-26 23:34 UTC, skyline75489 commented
I am no expert on security issue like this. I think this PR needs to be thoroughly reviewed.  Feel free to tag this to 1.7 or future release. No need to rush this one.

2021-01-29 08:50 UTC, skyline75489 commented
I *think* I should also add this to conhost. But I don't know conhost that much. I'll file a issue for conhost if this is merged.

2021-02-04 01:49 UTC, DHowett commented
I appreciate this, but I do think that it needs some changes.

I'm not a huge fan of the lambda filtering implementation; I think that it would be much better for us to have _one loop_ that checks for `\n` _and all the other control sequences at the same time._

As it is implemented in this PR, we scan the string to determine that it doesn't contain `\n`, and then we re-scan the portion between 0 and the first \n, then we re-scan the portion between that \n and the next one, and then ... (etc) to detect control sequences.

Same concern about the bracketed paste function. Why have a lambda?

Lastly- I wonder if this should be inside TerminalCore so that the WPF control can use it. Needing the correct filtering for \r\n _and_ for control sequences is not something unique to the TerminalControl!

2021-02-04 01:59 UTC, skyline75489 commented
The main reason I used lambda is to minimize the modification to the existing code. Yea it does introduced extra scan loop. I can’t blame you for wanting this to run faster. I’ll try to refactor  this later.

2021-02-04 07:00 UTC, skyline75489 commented
Closed in favor of #9034

2021-02-04 07:00 UTC, closed without merging